name = "OMOPCommonDataModel"
uuid = "ba65db9e-6590-4054-ab8a-101ed9124986"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics", "JuliaHealth", "and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
