name = "OMOPCommonDataModel"
uuid = "ba65db9e-6590-4054-ab8a-101ed9124986"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics", "JuliaHealth", "contributors"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"

[compat]
DataFrames = "1"
DocStringExtensions = "0.8, 0.9"
PrettyPrint = "0.2"
StructArrays = "0.4, 0.5, 0.6"
Tables = "1"
julia = "1.1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Documenter", "PrettyPrint", "StructArrays", "Tables", "Test"]
